version: '3.3'

services:
  db:
    container_name: fx-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "fxdemo"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db-config:/docker-entrypoint-initdb.d
      - fx-volume:/var/lib/mysql
volumes:
    fx-volume:
